# Practice Numpy

In [1]:
import numpy as np

In [2]:
# main datatyype ndarray
a = np.array([1,2,3]) #1-D array

In [3]:
a , type(a) , a.shape 

(array([1, 2, 3]), numpy.ndarray, (3,))

In [4]:
a2 = np.array([[1,2,3],
               [4,5,6]]) # 2-D array

In [5]:
a2 , type(a2) , a2.shape 

(array([[1, 2, 3],
        [4, 5, 6]]),
 numpy.ndarray,
 (2, 3))

In [6]:
#check  no.of dimensions
a.ndim , a2.ndim

(1, 2)

In [7]:
# size of an array(no. of elements)
a.size , a2.size

(3, 6)

In [8]:
# converting numpy to pandas
import pandas as pd
df = pd.DataFrame(a2)

In [9]:
df # we can perform both numpy and pandas func on any dataframe

0  1  2
0  1  2  3
1  4  5  6

#### Different types to create array

In [10]:
s_1 = np.ones((2,3) , dtype = 'int') # dtype int (by default float)
s_1

array([[1, 1, 1],
       [1, 1, 1]])

In [11]:
s_2 = np.zeros((2,3))
s_2

array([[0., 0., 0.],
       [0., 0., 0.]])

In [12]:
s_3 = np.arange(0,15,3)
s_3

array([ 0,  3,  6,  9, 12])

In [13]:
# using random func(randint) fills the size by random integers in between min and max numbers
s_4 = np.random.randint(4,20,size = (4,3))
s_4

array([[16, 13, 14],
       [15,  4,  5],
       [17, 16, 17],
       [ 9, 13,  4]])

In [14]:
# using random func(random) fills the size by random integers in between 0 and 1 
s_5 = np.random.random((4,5))
s_5

array([[0.43994208, 0.01317295, 0.93069369, 0.27347914, 0.23498923],
       [0.47241305, 0.44271235, 0.96562134, 0.72712748, 0.8902722 ],
       [0.45579059, 0.25407841, 0.46961812, 0.37041319, 0.06269745],
       [0.13679006, 0.54653184, 0.50567821, 0.00865505, 0.28762657]])

In [15]:
# to fix the random numbers to not change everytime
# seed is used
np.random.seed(6) # can be any number
s_6 = np.random.randint(10 , size=(2,6))
s_6

array([[9, 3, 4, 0, 9, 1],
       [9, 1, 4, 1, 8, 2]])

#### Manupulating Arrays

In [16]:
np.unique(s_4) # returns unique values in the array

array([ 4,  5,  9, 13, 14, 15, 16, 17])

In [17]:
s_4[1] # array slicing

array([15,  4,  5])

In [18]:
s_4[:2 , :2] , s_4.shape #[:x , :y] x is the rows , y is the cols

(array([[16, 13],
        [15,  4]]),
 (4, 3))

In [19]:
# matrix multiplication and addition
a

array([1, 2, 3])

In [20]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
a+a2 

array([[2, 4, 6],
       [5, 7, 9]])

In [22]:
a*a2

array([[ 1,  4,  9],
       [ 4, 10, 18]])

In [23]:
s_4 

array([[16, 13, 14],
       [15,  4,  5],
       [17, 16, 17],
       [ 9, 13,  4]])

In [24]:
np.sum(a2) # all types of aggregation tricks

21

In [25]:
np.median(s_4)

13.5

In [26]:
# %timeit is to print the time taken by a line of to run
# see list func or np func which is faster
a3 = np.random.random(1000000)
%timeit sum(a3) # python func (takes milli sec to run)
%timeit np.sum(a3) # numpy func (takes micro sec to run)

223 ms ± 8.34 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
799 µs ± 65.3 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [27]:
np.square(s_4)

array([[256, 169, 196],
       [225,  16,  25],
       [289, 256, 289],
       [ 81, 169,  16]], dtype=int32)

In [28]:
np.sqrt(s_4)

array([[4.        , 3.60555128, 3.74165739],
       [3.87298335, 2.        , 2.23606798],
       [4.12310563, 4.        , 4.12310563],
       [3.        , 3.60555128, 2.        ]])

In [29]:
# variance
high_var = np.array([1,100,1000,50000,100000]) # higher variance wider range of values
low_var = np.array([2,4,6,8,10]) # lower variance smaller range of values

In [30]:
np.var(high_var) , np.var(low_var)

(1586941512.16, 8.0)

In [31]:
#standard Deviation
# higher the var higher the std
# std is the distance from the mean to other ele
np.std(high_var) , np.std(low_var)

(39836.43448101248, 2.8284271247461903)

In [32]:
# mean
np.mean(high_var) , np.mean(low_var)

(30220.2, 6.0)

In [33]:
s_4

array([[16, 13, 14],
       [15,  4,  5],
       [17, 16, 17],
       [ 9, 13,  4]])

In [34]:
s_4.reshape(2,3,2) # changing shape of an array

array([[[16, 13],
        [14, 15],
        [ 4,  5]],

       [[17, 16],
        [17,  9],
        [13,  4]]])

In [35]:
s_4.transpose() #changes the axis

array([[16, 15, 17,  9],
       [13,  4, 16, 13],
       [14,  5, 17,  4]])

In [36]:
s_4.T # shortcut of transpose

array([[16, 15, 17,  9],
       [13,  4, 16, 13],
       [14,  5, 17,  4]])

#### Comparison

In [37]:
x = np.array([1,2,3,3,5,4,7])
y = np.array([2,5,2,1,6,3,7])

In [38]:
x>y # compares each element 

array([False, False,  True,  True, False,  True, False])

In [39]:
x<=y

array([ True,  True, False, False,  True, False,  True])

#### Images to numpy arrays

In [40]:
from matplotlib.image import imread

In [41]:
# 3 dim as 3 main colours red , green , blue
# converts each pixel to a number
panda = imread('numpy-panda.png') 

<img src='numpy-panda.png'/>

In [42]:
panda.ndim , panda.shape , panda.size

(3, (2330, 3500, 3), 24465000)

In [43]:
panda[:2]

array([[[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]]], dtype=float32)

In [44]:
car = imread('numpy-car-photo.png')

<img src ='numpy-car-photo.png' />

In [45]:
car.ndim , car.shape , car.size  # relatively less size than the panda

(3, (431, 575, 4), 991300)

In [46]:
car[:2]

array([[[0.5019608 , 0.50980395, 0.4862745 , 1.        ],
        [0.3372549 , 0.34509805, 0.30588236, 1.        ],
        [0.20392157, 0.21568628, 0.14901961, 1.        ],
        ...,
        [0.64705884, 0.7058824 , 0.54901963, 1.        ],
        [0.59607846, 0.63529414, 0.45882353, 1.        ],
        [0.44705883, 0.47058824, 0.3372549 , 1.        ]],

       [[0.44313726, 0.43529412, 0.40392157, 1.        ],
        [0.3137255 , 0.31764707, 0.27450982, 1.        ],
        [0.2       , 0.21176471, 0.14117648, 1.        ],
        ...,
        [0.5058824 , 0.5372549 , 0.4117647 , 1.        ],
        [0.49803922, 0.52156866, 0.39607844, 1.        ],
        [0.4       , 0.42745098, 0.34117648, 1.        ]]], dtype=float32)

In [47]:
dog = imread('numpy-dog-photo.png')

<img src ="numpy-dog-photo.png" />

In [48]:
dog.ndim , dog.shape , dog.size  # relatively less size than the panda

(3, (432, 575, 4), 993600)

In [49]:
dog[:2]

array([[[0.70980394, 0.80784315, 0.88235295, 1.        ],
        [0.72156864, 0.8117647 , 0.8862745 , 1.        ],
        [0.7411765 , 0.8156863 , 0.8862745 , 1.        ],
        ...,
        [0.49803922, 0.6862745 , 0.8392157 , 1.        ],
        [0.49411765, 0.68235296, 0.8392157 , 1.        ],
        [0.49411765, 0.68235296, 0.8352941 , 1.        ]],

       [[0.69411767, 0.8039216 , 0.8862745 , 1.        ],
        [0.7019608 , 0.8039216 , 0.88235295, 1.        ],
        [0.7058824 , 0.80784315, 0.88235295, 1.        ],
        ...,
        [0.5019608 , 0.6862745 , 0.84705883, 1.        ],
        [0.49411765, 0.68235296, 0.84313726, 1.        ],
        [0.49411765, 0.68235296, 0.8392157 , 1.        ]]], dtype=float32)